[project]
name = "code-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.2"
dependencies = [
    "datasets>=3.4.1",
    "lightning>=2.5.1",
    "mypy>=1.15.0",
    "sh>=2.2.2",
    "torch>=2.6.0",
    "transformers>=4.50.0",
]
