version: 2.1
orbs:
  codecov: codecov/codecov@3.2.5
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - add_ssh_keys:
          fingerprints:
            - "74:f0:71:3a:df:c0:a9:b7:39:46:26:4a:d8:8b:14:67"
      - checkout
      - run:
          name: build
          command: ./run ci